### ISSUE TITLE
How much GPU memory is needed for GPT-J

### ISSUE THREAD

**Issue by YerongLi** [xrsrke/toolformer#3]
With small **bigscience/bloom-560m** I can use do calculator in the README-example. While with GPT-J, I got OOM when I filter_api.

```
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attenti
on_mask` to obtain reliable results.    
Setting `pad_token_id` to `eos_token_id`:13 for open-end generation.                                                                          
Traceback (most recent call last):                                     
  File "/scratch/yerong/toolformer/example.py", line 54, in <module>                                                                          
    augumented_text_ids = generator.generate(text)                                                                                            
  File "/scratch/yerong/toolformer/toolformer/data_generator.py", line 426, in generate
    filtered_candidate_ids = self.filter_api(api, text_ids, api_start_idxs, candidate_ids)
  File "/scratch/yerong/toolformer/toolformer/data_generator.py", line 328, in filter_api
    output = self.model(input_ids=conditioning_text_ids.long())
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 852, in forward
    transformer_outputs = self.transformer(
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 687, in forward
    outputs = block(
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 320, in forward
    feed_forward_hidden_states = self.mlp(hidden_states)
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 281, in forward
    hidden_states = self.fc_in(hidden_states)
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/yerong/.conda/envs/tool/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 160.00 MiB (GPU 0; 47.54 GiB total capacity; 46.16 GiB already allocated; 1
47.56 MiB free; 46.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragm
entation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
(tool) [yerong2@ccc0325 toolformer]$ 
```

**Comment by YerongLi** [comment]
Enable low-memory mode fixed the issue.

**Comment by xrsrke** [comment]
@YerongLi that's awesome. I'm glad to hear it!
